# Generated by Django 5.0.2 on 2024-03-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_title'),
        ('leaveMan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('home_phone', models.IntegerField(blank=True, null=True)),
                ('mobile_phone', models.IntegerField(blank=True, null=True)),
                ('home_address', models.CharField(blank=True, max_length=150, null=True)),
                ('months_in_institution', models.IntegerField(blank=True, null=True)),
                ('total_leave_days', models.IntegerField(blank=True, null=True)),
                ('leave_days_used', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.title')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
