# Generated by Django 5.0.2 on 2024-04-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveMan', '0003_leave_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='inDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='outDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
