# Generated by Django 5.0.2 on 2024-05-22 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_companyemployee_department_and_more'),
        ('leaveMan', '0004_leave_indate_leave_outdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='department',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='title',
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companyemployee'),
        ),
    ]
