# Generated by Django 5.0.2 on 2024-05-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveMan', '0005_remove_leave_birth_date_remove_leave_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_days_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
