# Generated by Django 5.0.2 on 2024-05-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveMan', '0006_alter_leave_leave_days_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED')], default='PENDING', max_length=100),
        ),
    ]
