# Generated by Django 5.0.2 on 2024-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveMan', '0007_leave_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approval_one',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('DONE', 'DONE')], default='PENDING', max_length=100),
        ),
    ]
