# Generated by Django 5.0.2 on 2024-05-31 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_employeeasusersignature'),
        ('leaveMan', '0008_leave_approval_one_alter_leave_leave_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisionStatus', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('approvingEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveMan.leave')),
                ('requestingEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_leaves', to='company.companyemployee')),
            ],
        ),
    ]
