# Generated by Django 5.0.2 on 2024-07-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_employeeasusersignature'),
        ('leaveMan', '0009_leavedecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedecision',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.employeeasusersignature'),
        ),
    ]
