# Generated by Django 5.0.2 on 2024-08-06 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_umumaro_companyemployee_role'),
        ('leaveMan', '0010_leavedecision_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedecision',
            name='approvingEmployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_leaves', to='company.companyemployee'),
        ),
    ]
