# Generated by Django 5.0.2 on 2024-03-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondPartyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icparsa.department')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('contract_type', models.CharField(choices=[('Temporary', 'Temporary'), ('Permanent', 'Permanent')], max_length=250, null=True)),
                ('addressed_department', models.CharField(choices=[('SIS', 'SIS'), ('EDS', 'EDS'), ('PSD', 'PDS')], max_length=250, null=True)),
                ('contract_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CANCELED', 'CANCELED')], default='APPROVED', max_length=100)),
                ('signedDate', models.DateField(blank=True, null=True)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('department', models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icparsa.department')),
                ('secondParty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icparsa.secondparty')),
            ],
        ),
        migrations.AddField(
            model_name='secondparty',
            name='spType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icparsa.secondpartytype'),
        ),
    ]
