# Generated by Django 5.0.2 on 2024-03-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='addressed_department',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_status',
            field=models.CharField(choices=[('SIGNED', 'SIGNED'), ('CANCELED', 'CANCELED')], default='SIGNED', max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('Framework', 'Framework contract'), ('Determined', 'Others')], max_length=250, null=True),
        ),
    ]
