# Generated by Django 5.0.2 on 2024-03-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0002_remove_contract_addressed_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='departmentUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icparsa.departmentmember'),
        ),
    ]
