# Generated by Django 5.0.2 on 2024-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0004_departmentmember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notificationSent',
            field=models.BooleanField(default=False),
        ),
    ]
