# Generated by Django 5.0.2 on 2024-03-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0005_contract_notificationsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationNumber', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
