# Generated by Django 5.0.2 on 2024-03-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0006_contractsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractsetting',
            old_name='expirationNumber',
            new_name='expirationDays',
        ),
    ]
