# Generated by Django 5.0.2 on 2024-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0007_rename_expirationnumber_contractsetting_expirationdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsetting',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contractsetting',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contractsetting',
            name='type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
