# Generated by Django 5.0.2 on 2024-04-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0010_contract_contracttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_type',
        ),
    ]
