# Generated by Django 5.0.2 on 2024-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0011_remove_contract_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsetting',
            name='remindingTimes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
