# Generated by Django 5.0.2 on 2024-05-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0012_contractsetting_remindingtimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notificationSentOn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='notification_Sent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
