# Generated by Django 5.0.2 on 2024-05-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0013_contract_notificationsenton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsetting',
            name='notificationsDaysToWait',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
