# Generated by Django 5.0.2 on 2024-05-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0015_rename_notification_sent_contract_notificationremindingtimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notificationWaitingInterval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
