# Generated by Django 5.0.2 on 2024-05-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0016_contract_notificationwaitinginterval'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsetting',
            name='managingEmail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
