# Generated by Django 5.0.2 on 2024-05-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0018_department_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsetting',
            name='renewTimes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
