# Generated by Django 5.0.2 on 2024-05-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0019_contractsetting_renewtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsetting',
            name='renewTimes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
