# Generated by Django 5.0.2 on 2024-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0022_contracthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracthistory',
            name='renewDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
