# Generated by Django 5.0.2 on 2024-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0023_contracthistory_renewdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracthistory',
            name='renewalCounter',
            field=models.IntegerField(default=0),
        ),
    ]
