# Generated by Django 5.0.2 on 2024-05-14 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0025_contractsettingname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsetting',
            name='contractName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icparsa.contractsettingname'),
        ),
    ]
