# Generated by Django 5.0.2 on 2024-05-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0027_contract_contractcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractsetting',
            name='type',
        ),
    ]
