# Generated by Django 5.0.2 on 2024-05-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icparsa', '0028_remove_contractsetting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='notificationRemindingTimes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
