# Generated by Django 5.0.2 on 2024-04-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_companyemployee_emp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.TextField(blank=True, max_length=250, null=True)),
                ('reference_number', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('responsible', models.CharField(blank=True, max_length=150, null=True)),
                ('correspondence_type', models.CharField(blank=True, choices=[('INCOMING', 'INCOMING'), ('OUTGOING', 'GOING')], max_length=250, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department')),
            ],
        ),
    ]
