# Generated by Django 5.0.2 on 2024-04-04 15:20

import django.db.models.fields.related
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_title_unit'),
        ('correspondence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='unit',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='company.unit'),
        ),
    ]
