# Generated by Django 5.0.2 on 2024-03-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.RemoveField(
            model_name='title',
            name='company',
        ),
        migrations.RemoveField(
            model_name='title',
            name='department',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
