# Generated by Django 5.0.2 on 2024-04-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyemployee',
            name='leave_days_used',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='months_in_institution',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='total_leave_days',
        ),
    ]
