# Generated by Django 5.0.2 on 2024-04-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_companyemployee_leave_days_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployee',
            name='emp_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
