# Generated by Django 5.0.2 on 2024-04-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.unit'),
        ),
    ]
