# Generated by Django 5.0.2 on 2024-05-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_title_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
