# Generated by Django 5.0.2 on 2024-05-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_email_companyemployee_email_department_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.title'),
        ),
    ]
